// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

import 'dart:ffi' as ffi;
import 'dart:ffi';

// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names

class NwbfilePluginBindings {
  final ffi.DynamicLibrary _dylib;

  NwbfilePluginBindings(this._dylib);

  // Basic math functions
  int sum(int a, int b) => _dylib.lookupFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32), int Function(int, int)>('sum')(a, b);
  
  int sum_long_running(int a, int b) => _dylib.lookupFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32), int Function(int, int)>('sum_long_running')(a, b);

  int processing_update(Pointer<Char> path) => _dylib.lookupFunction<ffi.Int32 Function(Pointer<Char>), int Function(Pointer<Char>)>('processing_update')(path);

  // NWB processing functions
  int processing_init(Pointer<Char> path, int sampleRate, int channelCount) => _dylib.lookupFunction<ffi.Int32 Function(Pointer<Char>, ffi.Int32, ffi.Int32), int Function(Pointer<Char>, int, int)>('processing_init')(path, sampleRate, channelCount);
  int nwbfile_add_electrical_series(Pointer<Int16> inSamples, Pointer<Int32> samplesCount, int selectedChannel, int channelCount, int isFinishRecording) => _dylib.lookupFunction<ffi.Int32 Function(Pointer<Int16>, Pointer<Int32>, ffi.Int32, ffi.Int32, ffi.Int32), int Function(Pointer<Int16>, Pointer<Int32>, int, int, int)>('nwbfile_add_electrical_series')(inSamples, samplesCount, selectedChannel, channelCount, isFinishRecording);
  int nwbfile_read_electrical_series(Pointer<Int16> outSamples, Pointer<Int32> outSampleCounts, int selectedChannel, int channelCount) => _dylib.lookupFunction<ffi.Int32 Function(Pointer<Int16>, Pointer<Int32>, ffi.Int32, ffi.Int32), int Function(Pointer<Int16>, Pointer<Int32>, int, int)>('nwbfile_read_electrical_series')(outSamples, outSampleCounts, selectedChannel, channelCount);

  int nwbfile_seek_electrical_series(Pointer<Int16> outSamples, Pointer<Int32> outSampleCounts, Pointer<Int32> outConfig, int startTimeStamp, int endTimeStamp, int selectedChannel, int channelCount) => _dylib.lookupFunction<ffi.Int32 Function(Pointer<Int16>, Pointer<Int32>, Pointer<Int32>, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(Pointer<Int16>, Pointer<Int32>, Pointer<Int32>, int, int, int, int)>('nwbfile_seek_electrical_series')(outSamples, outSampleCounts, outConfig, startTimeStamp, endTimeStamp, selectedChannel, channelCount);
  
  int get_nwb_file_size() => _dylib.lookupFunction<ffi.Int32 Function(), int Function()>('get_nwb_file_size')();
  
  int get_nwb_file_data(ffi.Pointer<ffi.Char> buffer, int buffer_size) => _dylib.lookupFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Int32), int Function(ffi.Pointer<ffi.Char>, int)>('get_nwb_file_data')(buffer, buffer_size);
  
  void cleanup_nwb_data() => _dylib.lookupFunction<ffi.Void Function(), void Function()>('cleanup_nwb_data')();
}
