#include "nwbfile_processing_plugin.hpp"
#include <memory>
#include <string>
#include <vector>
#include <thread>
#include <chrono>


#include "Utils.hpp"
#include "Channel.hpp"
#include "nwb/NWBFile.hpp"
#include "nwb/RecordingContainers.hpp"
#include "../include/H5Cpp.h"

// Global buffer to store NWB file data
std::vector<uint8_t> g_nwb_file_data;
bool g_nwb_file_ready = false;


// A very short-lived native function.
//
// For very short-lived functions, it is fine to call them on the main isolate.
// They will block the Dart execution while running the native function, so
// only do this for native functions which are guaranteed to be short-lived.
FFI_PLUGIN_EXPORT int sum(int a, int b) { return a + b; }

// A longer-lived native function, which occupies the thread calling it.
//
// Do not call these kind of native functions in the main isolate. They will
// block Dart execution. This will cause dropped frames in Flutter applications.
// Instead, call these native functions on a separate isolate.
FFI_PLUGIN_EXPORT int sum_long_running(int a, int b) {
  // Simulate work.
#if _WIN32
  Sleep(5000);
#else
  std::this_thread::sleep_for(std::chrono::milliseconds(5000));
#endif
  return a + b;
}

// Processing initialization function
FFI_PLUGIN_EXPORT int32_t processing_init(const char* path, int sampleRate, int channelCount, const char* deviceInfo, const char* deviceManufacturer) {
    try {
      H5::Exception::dontPrint();
      printf("AAQNWB Recording Workflow Example\n");
      printf("================================\n");
      printf("%s\n", std::string(path).c_str());
      printf("================================\n");
  
      // 1) Create the I/O object
      // /Users/macbook/Library/Containers/com.example.nwbapplication/Data/Documents A1E49CB1
      // /Users/macbook/Library/Containers/com.example.nwbapplication/Data/Downloads/
    //   const std::string outputPath = "/var/mobile/Containers/Data/Application/201ECF83-6002-4632-BD12-31B61796EF46/Documents/example_recording2.nwb";
      const std::string outputPath = std::string(path) + "/example_recording2.nwb";
      std::shared_ptr<AQNWB::IO::BaseIO> io = AQNWB::createIO("HDF5", outputPath);
      auto openStatus = io->open(AQNWB::IO::FileMode::Overwrite);
      if (openStatus != AQNWB::Types::Success) {
          printf("Failed to open IO\n");
          return 1;
      }
  
      // 2) Create the RecordingContainers object
      std::unique_ptr<AQNWB::NWB::RecordingContainers> recordingContainers =
          std::make_unique<AQNWB::NWB::RecordingContainers>();
  
      // 3) Create and initialize the NWBFile
      std::unique_ptr<AQNWB::NWB::NWBFile> nwbfile = std::make_unique<AQNWB::NWB::NWBFile>(io);
      auto initStatus = nwbfile->initialize(AQNWB::generateUuid(),
                                            "Example ecephys session",
                                            "Generated by AqNWB example");
      if (initStatus != AQNWB::Types::Success) {
          printf("Failed to initialize NWB file\n");
          return 1;
      }
  
      // 4) Create recording metadata (ElectrodesTable)
      // Build a mock recording array: one array with 4 channels
      std::vector<AQNWB::Types::ChannelVector> recordingArrays;
      {
          AQNWB::Types::ChannelVector array1;
          const std::string groupName = "Array1";
          const AQNWB::Types::SizeType groupIndex = 0;
          for (AQNWB::Types::SizeType ch = 0; ch < 4; ++ch) {
              // name, groupName, groupIndex, localIndex, globalIndex, conversion, samplingRate, bitVolts
              array1.emplace_back(
                  "chan_" + std::to_string(ch),
                  groupName,
                  groupIndex,
                  ch,               // local index within array
                  ch,               // global index across system (mock)
                  1e6f,             // convert uV->V
                  30000.f,          // sampling rate
                  0.195f            // bitVolts
              );
          }
          recordingArrays.emplace_back(std::move(array1));
      }
  
      auto elecTableStatus = nwbfile->createElectrodesTable(recordingArrays);
      if (elecTableStatus != AQNWB::Types::Success) {
          printf("Failed to create electrodes table\n");
          return 1;
      }
  
      // 5) Create datasets (ElectricalSeries) and add to RecordingContainers
      std::vector<std::string> recordingNames = {"ElectricalSeries1"};
      std::vector<AQNWB::Types::SizeType> containerIndexes;
      auto elecSeriesStatus = nwbfile->createElectricalSeries(
          recordingArrays,
          recordingNames,
          AQNWB::IO::BaseDataType::I16,
          recordingContainers.get(),
          containerIndexes);
      if (elecSeriesStatus != AQNWB::Types::Success) {
          printf("Failed to create ElectricalSeries\n");
          return 1;
      }
  
      // 6) Start the recording
      auto startRecordingStatus = io->startRecording();
      if (startRecordingStatus != AQNWB::Types::Success) {
          printf("Failed to start recording\n");
          return 1;
      }
  
      // 7) Write data
      // Simulate writing a short block of data for each channel in the first ElectricalSeries
      const AQNWB::Types::SizeType containerIndex = containerIndexes.at(0);
      const auto& channels = recordingArrays[0];
      const AQNWB::Types::SizeType numSamples = 1000; // samples per write
  
      // timestamps at 30 kHz
      std::vector<double> timestamps(numSamples);
      const double samplingRate = static_cast<double>(channels[0].getSamplingRate());
      const double dt = 1.0 / samplingRate;
      for (AQNWB::Types::SizeType i = 0; i < numSamples; ++i) {
          timestamps[i] = static_cast<double>(i) * dt;
      }
  
      // write data per-channel
      for (const auto& ch : channels) {
          std::vector<int16_t> data(numSamples);
          for (AQNWB::Types::SizeType i = 0; i < numSamples; ++i) {
              // simple mock waveform for demonstration
              data[i] = static_cast<int16_t>((i % 200) - 100);
          }
  
          auto writeStatus = recordingContainers->writeElectricalSeriesData(
              containerIndex,
              ch,
              numSamples,
              static_cast<const void*>(data.data()),
              static_cast<const void*>(timestamps.data()));
  
          if (writeStatus != AQNWB::Types::Success) {
              printf("Failed to write data for channel %s\n", ch.getName().c_str());
              return 1;
          }
      }
  
      // Ensure data is flushed to disk
      auto flushStatus = io->flush();
      if (flushStatus != AQNWB::Types::Success) {
          printf("Flush failed\n");
          return 1;
      }
  
      // 8) Stop recording and finalize the file
      auto stopRecordingStatus = io->stopRecording();
      if (stopRecordingStatus != AQNWB::Types::Success) {
          printf("Failed to stop recording\n");
          return 1;
      }
  
      auto finalizeStatus = nwbfile->finalize();
      if (finalizeStatus != AQNWB::Types::Success) {
          printf("Failed to finalize NWB file\n");
          return 1;
      }
  
      auto closeStatus = io->close();
      if (closeStatus != AQNWB::Types::Success) {
          printf("Failed to close IO\n");
          return 1;
      }
  
      printf("Successfully wrote example recording to: %s\n", outputPath.c_str());
        std::shared_ptr<AQNWB::IO::BaseIO> readio = AQNWB::createIO("HDF5", outputPath);
      readio->open(AQNWB::IO::FileMode::ReadOnly);
        auto readNWBFile =
            AQNWB::NWB::RegisteredType::create<AQNWB::NWB::NWBFile>("/", readio);
        // Read the ElectrodesTable
        auto readElectrodeTable = readNWBFile->readElectrodeTable();
        // read the location data. Note that both the type of the class and
        // the data values is being set for us, here, VectorDataTyped<std::string>
        auto locationColumn = readElectrodeTable->readLocationColumn();
        auto locationColumnValues = locationColumn->readData()->values();
        locationColumnValues.data.size();
      // Store the NWB file data in our global buffer
      // For now, we'll create a simple mock NWB file structure
      g_nwb_file_data.clear();
      
      // Create a simple mock NWB file header
      std::string mock_nwb_content = 
          "NWB File WRITE\n"
          "Version: 2.0\n"
          "Created: " + outputPath + "\n"
          "Electrodes: 4\n"
          "ElectricalSeries: 1\n"
          "Data Points: 1000\n"
          "Sampling Rate: 30000 Hz\n"
          "File Size: Mock Data\n";
      
      g_nwb_file_data.assign(mock_nwb_content.begin(), mock_nwb_content.end());
      g_nwb_file_ready = true;
      
      return 0;
    } catch (const std::exception& e) {
        printf("Error: %s\n", e.what());
        return 1;
    }    
    return -1;
  }
  
  // Function to get the NWB file data
  FFI_PLUGIN_EXPORT int get_nwb_file_size() {
      if (!g_nwb_file_ready) {
          return -1; // File not ready
      }
      return static_cast<int>(g_nwb_file_data.size());
  }
  
  // Function to copy NWB file data to a provided buffer
  FFI_PLUGIN_EXPORT int get_nwb_file_data(uint8_t* buffer, int buffer_size) {
      if (!g_nwb_file_ready) {
          return -1; // File not ready
      }
      
      if (buffer == nullptr || buffer_size < static_cast<int>(g_nwb_file_data.size())) {
          return -2; // Invalid buffer or buffer too small
      }
      
      std::copy(g_nwb_file_data.begin(), g_nwb_file_data.end(), buffer);
      return static_cast<int>(g_nwb_file_data.size());
  }
  
