#include "nwbfile_processing_plugin.hpp"
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <cstdarg>
#include <algorithm>

#include "Utils.hpp"
#include "Channel.hpp"
#include "nwb/NWBFile.hpp"
#include "nwb/misc/AnnotationSeries.hpp"
#include "nwb/RecordingContainers.hpp"
#include "nwb/device/Device.hpp"
#include "nwb/ecephys/ElectricalSeries.hpp"
#include <H5Cpp.h>

#include <string>
#define IS_WIN32 defined(WIN32) || defined(_WIN32) || defined(__WIN32)
void file_log_nwbfile(const char *fmt, ...) {
    va_list args;
    va_start(args, fmt);
#ifdef __ANDROID__
    __android_log_vprint(ANDROID_LOG_VERBOSE, "ndk", fmt, args);
#else
    vprintf(fmt, args);
#endif
    va_end(args);
}

// Global buffer to store NWB file data (for web version)
std::vector<uint8_t> g_nwb_file_data;
bool g_nwb_file_ready = false;

// Global state for NWB file operations
std::shared_ptr<AQNWB::IO::BaseIO> io;
std::unique_ptr<AQNWB::NWB::NWBFile> nwbfile;
std::unique_ptr<AQNWB::NWB::RecordingContainers> recordingContainers;
std::vector<AQNWB::Types::ChannelVector> recordingArrays;
std::vector<AQNWB::Types::SizeType> containerIndexes;
std::string outputPath;

// A very short-lived native function.
//
// For very short-lived functions, it is fine to call them on the main isolate.
// They will block the Dart execution while running the native function, so
// only do this for native functions which are guaranteed to be short-lived.
FFI_PLUGIN_EXPORT int sum(int a, int b) { return a + b; }

// A longer-lived native function, which occupies the thread calling it.
//
// Do not call these kind of native functions in the main isolate. They will
// block Dart execution. This will cause dropped frames in Flutter applications.
// Instead, call these native functions on a separate isolate.
FFI_PLUGIN_EXPORT int sum_long_running(int a, int b) {
  // Simulate work.
#if _WIN32
  Sleep(5000);
#else
  usleep(5000 * 1000);
#endif
  return a + b;
}

// Processing initialization function (web version with HDF5 via Emscripten)
FFI_PLUGIN_EXPORT int32_t processing_init(const char* path, int sampleRate, int channelCount, const char* deviceInfo, const char* deviceManufacturer) {
    try {
        H5::Exception::dontPrint();
        std::cout << "AQNWB Recording Workflow Example (Web Version)" << std::endl;
        std::cout << "================================" << std::endl;
    
        // 1) Create the I/O object
        // For web, path is relative to Emscripten's virtual file system
        outputPath = path;
        io = AQNWB::createIO("HDF5", outputPath);
        auto openStatus = io->open(AQNWB::IO::FileMode::Overwrite);
        
        if (openStatus != AQNWB::Types::Success) {
            std::cerr << "Failed to open IO" << std::endl;
            return 1;
        }

        // 2) Create the RecordingContainers object
        recordingContainers = std::make_unique<AQNWB::NWB::RecordingContainers>();
    
        // 3) Create and initialize the NWBFile
        nwbfile = std::make_unique<AQNWB::NWB::NWBFile>(io);
        auto initStatus = nwbfile->initialize(AQNWB::generateUuid(),
                                                "Example ecephys session",
                                                "Generated by AqNWB example");
        if (initStatus != AQNWB::Types::Success) {
            std::cerr << "Failed to initialize NWB file" << std::endl;
            return 1;
        }

        // 3.5) Add device information (AFTER NWBFile initialization)
        std::cout << "Adding device information..." << std::endl;
        std::unique_ptr<AQNWB::NWB::Device> device = 
            std::make_unique<AQNWB::NWB::Device>("/general/devices/recording_device", io);
        
        // Initialize the device with description and manufacturer
        device->initialize(deviceInfo, deviceManufacturer);
        
        std::cout << "Device information added successfully" << std::endl;
        std::cout << "Device Description: " << deviceInfo << std::endl;
        std::cout << "Device Manufacturer: " << deviceManufacturer << std::endl;
        std::cout << "Init Status: " << initStatus << "  " << channelCount << std::endl;

        // 4) Create recording metadata (ElectrodesTable)
        std::vector<AQNWB::Types::ChannelVector> tempRecordingArrays;
        {
            AQNWB::Types::ChannelVector array1;
            const std::string groupName = "Array1";
            const AQNWB::Types::SizeType groupIndex = 0;
            for (AQNWB::Types::SizeType ch = 0; ch < channelCount; ++ch) {
                // name, groupName, groupIndex, localIndex, globalIndex, conversion, samplingRate, bitVolts
                array1.emplace_back(
                    "chan_" + std::to_string(ch),
                    groupName,
                    groupIndex,
                    ch,               // local index within array
                    ch,               // global index across system (mock)
                    1e6f,             // convert uV->V (correct conversion factor)
                    static_cast<float>(sampleRate),  // sampling rate
                    0.195f            // bitVolts (correct bit volts)
                );
            }
            tempRecordingArrays.emplace_back(std::move(array1));
        }
        recordingArrays = tempRecordingArrays;
        auto elecTableStatus = nwbfile->createElectrodesTable(recordingArrays);
        if (elecTableStatus != AQNWB::Types::Success) {
            std::cerr << "Failed to create electrodes table" << std::endl;
            return 1;
        }
    
        std::cout << "Recording arrays & table created: " << channelCount << std::endl;
        std::vector<std::string> recordingNames = {"ElectricalSeries1"};
        
        // Create ONE ElectricalSeries for all channels (not one per channel)
        auto elecSeriesStatus = nwbfile->createElectricalSeries(
            recordingArrays,
            recordingNames,
            AQNWB::IO::BaseDataType::I16,
            recordingContainers.get(),
            containerIndexes);
        if (elecSeriesStatus != AQNWB::Types::Success) {
            std::cerr << "Failed to create ElectricalSeries" << std::endl;
            return 1;
        }
    
        std::cout << "START RECORDING" << 111.0 << std::endl;

        auto startRecordingStatus = io->startRecording();
        if (startRecordingStatus != AQNWB::Types::Success) {
            std::cerr << "Failed to start recording" << std::endl;
            return 1;
        }
    
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }    
    return -1;
}

int mutliplier = 0;
int numSamplesCounter = 0;
FFI_PLUGIN_EXPORT int32_t nwbfile_add_electrical_series(short* inSamples, int* samplesCount, int selectedChannel, int channelCount, int isFinishRecording) {
    
    // Validate input parameters
    if (!inSamples || !samplesCount || channelCount <= 0) {
        std::cerr << "Invalid input parameters" << std::endl;
        return -1;
    }
    
    // Validate sample counts to prevent buffer overruns
    for (int i = 0; i < channelCount; i++) {
        if (samplesCount[i] <= 0) {
            std::cerr << "Invalid sample count for channel " << i << ": " << samplesCount[i] << std::endl;
            return -1;
        }
    }
    
    short** arrSamples = nullptr;
    try {
        // Allocate memory for channel pointers
        arrSamples = new short*[channelCount];
        
        // Initialize all pointers to nullptr for safe cleanup
        for (int i = 0; i < channelCount; i++) {
            arrSamples[i] = nullptr;
        }
        
        // Allocate memory for each channel
        for (int i = 0; i < channelCount; i++) {
            try {
                arrSamples[i] = new short[samplesCount[i]];
                std::copy(inSamples + i * samplesCount[i], inSamples + (i + 1) * samplesCount[i], arrSamples[i]);
            } catch (const std::bad_alloc& e) {
                std::cerr << "Memory allocation failed for channel " << i << ": " << e.what() << std::endl;
                // Clean up already allocated memory
                for (int j = 0; j < i; j++) {
                    delete[] arrSamples[j];
                }
                delete[] arrSamples;
                return -1;
            }
        }

        const AQNWB::Types::SizeType containerIndex = containerIndexes.at(0);
        const auto& channels = recordingArrays[0];
        const AQNWB::Types::SizeType numSamples = samplesCount[0]; // samples per write

        // timestamps at sample rate
        std::vector<double> timestamps(numSamples);
        const double samplingRate = static_cast<double>(channels[0].getSamplingRate());
        const double dt = 1.0 / samplingRate;
        numSamplesCounter += numSamples;
        mutliplier = numSamplesCounter / samplingRate;
        for (AQNWB::Types::SizeType i = 0; i < numSamples; ++i) {
            timestamps[i] = (numSamplesCounter + i) * dt;
        }

        // Write data per-channel
        int channelIndex = 0;
        for (const auto& ch : channels) {
            auto writeStatus = recordingContainers->writeElectricalSeriesData(
                containerIndex,
                ch,
                samplesCount[channelIndex],
                static_cast<const void*>(arrSamples[channelIndex]),
                static_cast<const void*>(timestamps.data()));

            if (writeStatus != AQNWB::Types::Success) {
                std::cout << "WRITE ERROR " << samplesCount[channelIndex] << " CHANNEL: " << channelIndex << std::endl;
                std::cerr << "Failed to write data for channel " << ch.getName() << writeStatus << std::endl;
                // Clean up memory before returning
                if (arrSamples != nullptr) {
                    for (int i = 0; i < channelCount; i++) {
                        if (arrSamples[i] != nullptr) {
                            delete[] arrSamples[i];
                        }
                    }
                    delete[] arrSamples;
                }                
                return 1;
            }
            channelIndex++;        
        }

        // Ensure data is flushed to disk
        auto flushStatus = io->flush();
        if (flushStatus != AQNWB::Types::Success) {
            std::cerr << "Flush failed" << std::endl;
            // Clean up memory before returning
            if (arrSamples != nullptr) {
                for (int i = 0; i < channelCount; i++) {
                    if (arrSamples[i] != nullptr) {
                        delete[] arrSamples[i];
                    }
                }
                delete[] arrSamples;
            }
            return 1;
        }

        if (isFinishRecording == 1) {
        // 8) Stop recording and finalize the file
            auto stopRecordingStatus = io->stopRecording();
            if (stopRecordingStatus != AQNWB::Types::Success) {
                std::cerr << "Failed to stop recording" << std::endl;
                return 1;
            }
        
            auto finalizeStatus = nwbfile->finalize();
            if (finalizeStatus != AQNWB::Types::Success) {
                std::cerr << "Failed to finalize NWB file" << std::endl;
                return 1;
            }
        
            std::cout << "Successfully wrote example recording to: " << outputPath << std::endl;
    
            // Clean up memory
            if (arrSamples != nullptr) {
                for (int i = 0; i < channelCount; i++) {
                    if (arrSamples[i] != nullptr) {
                        delete[] arrSamples[i];
                    }
                }
                delete[] arrSamples;
            }
        
            // Close IO after finalization (matching reference order)
            auto closeStatus = io->close();
            if (closeStatus != AQNWB::Types::Success) {
                std::cerr << "Failed to close IO" << std::endl;
                return 1;
            }
            std::cout << "\n=== IO CLOSED ===" << std::endl;

        } else {
            // Clean up memory for non-finishing calls
            if (arrSamples != nullptr) {
                for (int i = 0; i < channelCount; i++) {
                    if (arrSamples[i] != nullptr) {
                        delete[] arrSamples[i];
                    }
                }
                delete[] arrSamples;
            }
        }
        
    } catch (const std::exception& e) {
        std::cerr << "Error in nwbfile_add_electrical_series: " << e.what() << std::endl;
        // Clean up memory in case of exception
        if (arrSamples != nullptr) {
            for (int i = 0; i < channelCount; i++) {
                if (arrSamples[i] != nullptr) {
                    delete[] arrSamples[i];
                }
            }
            delete[] arrSamples;
        }
        return 1;
    }
    
    return 0; // Success
}

// Function to get the NWB file size (for web version - file is in virtual FS)
FFI_PLUGIN_EXPORT int get_nwb_file_size() {
    // For web, the file is in Emscripten's virtual file system
    // We return -1 to indicate the file should be read from FS directly
    // The JavaScript code will use FS.readFile() instead
    return -1;
}

// Function to copy NWB file data to a provided buffer (for web version)
FFI_PLUGIN_EXPORT int get_nwb_file_data(uint8_t* buffer, uint32_t* buffer_size, uint32_t* buffer_size_raw, int start_size, int end_size) {
    // For web, files are accessed via Emscripten's FS, not through this function
    // Return error to indicate JavaScript should use FS.readFile() instead
    return -1;
}

// Stub implementations for other functions (can be implemented later if needed)
FFI_PLUGIN_EXPORT int32_t nwbfile_read_electrical_series(short* outSamples, int* outSamplesCount, int selectedChannel, int channelCount) {
    // Not implemented for web yet
    return -1;
}

FFI_PLUGIN_EXPORT int32_t debug_nwb_file_structure(const char* filePath) {
    // Not implemented for web yet
    return -1;
}

FFI_PLUGIN_EXPORT int32_t nwbfile_seek_electrical_series(const char* path, short* outSamples, int* outSamplesCount, int* outConfig, int startTimeStamp, int endTimeStamp, int startChannel, int endChannel) {
    // Not implemented for web yet
    return -1;
}


